# Generated by Django 3.2 on 2022-12-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20221228_2351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_time'], 'verbose_name_plural': 'news'},
        ),
    ]
